**Guarda Tutte le lezioni di NumPy qui**<br>
➡️➡️ [NumPy Playlist](https://www.youtube.com/watch?v=z0gMBWlScmw&list=PLqzZ6UmyLu115CH8xn6TLxxn8yDn7upOo)<br>
**Se hai qualche domanda o vuoi scrivermi**<br> 🙂
➡️➡️ [Linkedln](https://www.linkedin.com/in/rafaelc1532/)<br>
*Corso di numpy creato da Rafael Carpio*

In [ ]:
import numpy as np

In [ ]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr = np.array(lista)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
matrice = [[1,2,3], [4,5,6], [7,8,9]]
matrice = np.array(matrice)
matrice

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[8]

9

In [ ]:
arr[0] + arr[5]

7

In [ ]:
matrice[2]

array([7, 8, 9])

In [ ]:
matrice[2,2]

9

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [ ]:
arr[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[::4]

array([1, 5, 9])

In [ ]:
arr[-4]

6

In [ ]:
arr[-3:]

array([7, 8, 9])

In [ ]:
matrice[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrice

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrice[0:, 0:1]

array([[1],
       [4],
       [7]])