**Guarda Tutte le lezioni di NumPy qui**<br>
➡️➡️ [NumPy Playlist](https://www.youtube.com/watch?v=z0gMBWlScmw&list=PLqzZ6UmyLu115CH8xn6TLxxn8yDn7upOo)<br>
**Se hai qualche domanda o vuoi scrivermi**<br> 🙂
➡️➡️ [Linkedln](https://www.linkedin.com/in/rafaelc1532/)<br>
*Corso di numpy creato da Rafael Carpio*

💻***CODE***💻

### Importare la libreria di NumPy

In [ ]:
import numpy as np

# **Lista Vs. Array**

In [ ]:
#Lista
[1,2,3,4]

[1, 2, 3, 4]

***Transformiamo la lista in un Array***

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

***Che Tipo di Array Abbiamo?***

In [ ]:
arr.dtype

dtype('int64')

**Abbiamo davvero bisogno di 64 bit per uno, due, tre e quatro?.**

In [ ]:
# Esempio di conversione da decimale a binario
print(bin(1))
print(bin(2))
print(bin(3))
print(bin(4))

0b1
0b10
0b11
0b100


In [ ]:
arr2 =np.array([1,2,3,4], dtype='int8')
arr2

array([1, 2, 3, 4], dtype=int8)

### Cambiare il tipo del Array

Possiamo cambiare il tipo di dato a Float per esempio



In [ ]:
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

In [ ]:
arr

array([1., 2., 3., 4.])

In [ ]:
arr = np.array([0,1,2,3,4])
arr.dtype

dtype('int64')

In [ ]:
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [ ]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [ ]:
arr = np.array(['15','1','2','3','4'])
arr = arr.astype(np.int8)
arr

array([15,  1,  2,  3,  4], dtype=int8)