**Guarda Tutte le lezioni di NumPy qui**<br>
➡️➡️ [NumPy Playlist](https://www.youtube.com/watch?v=z0gMBWlScmw&list=PLqzZ6UmyLu115CH8xn6TLxxn8yDn7upOo)<br>
**Se hai qualche domanda o vuoi scrivermi**<br> 🙂
➡️➡️ [Linkedln](https://www.linkedin.com/in/rafaelc1532/)<br>
*Corso di numpy creato da Rafael Carpio*

## Importare librería

In [ ]:
import numpy as np

## Definire Array

In [ ]:
scalar = np.array(42)
print ("il valore di scalare è: ", scalar)

il valore di scalare è:  42


In [ ]:
print ("La quantita di dimensioni: ", scalar.ndim)

La quantita di dimensioni:  0


In [ ]:
vector = np.array([1, 2, 3])
print(f"i valori del vettore: {vector}, Il vettore ha {vector.ndim} dimensione")


i valori del vettore: [1 2 3], Il vettore ha 1 dimensione


In [ ]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim
print ("Questa Matrice ha "  + str(matriz.ndim) + " dimensioni")

[[1 2 3]
 [4 5 6]]
Questa Matrice ha 2 dimensioni


In [ ]:
tensor = np.array([[[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[4,2,3],[8,8,8],[7,8,9],[0,2,45]]]])

print(f"i valori del tensor: {tensor}, Il tensore ha {tensor.ndim} dimensioni")


i valori del tensor: [[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [ 0  2 45]]

  [[ 4  2  3]
   [ 8  8  8]
   [ 7  8  9]
   [ 0  2 45]]]], Il tensore ha 4 dimensioni


## Aggiungi o rimuovi dimensioni

In [ ]:
vector

array([1, 2, 3])

In [ ]:
vector = np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim


[[[[[[[[[[1 2 3]]]]]]]]]]


10

Espande la dimensione sull'asse X

In [ ]:
expandir = np.expand_dims(np.array([1,2,3]),axis=0)
print(expandir)
expandir.ndim
print(f"i valori del Array: {expandir}, Il Array ha {expandir.ndim} dimensioni")

[[1 2 3]]
i valori del Array: [[1 2 3]], Il Array ha 2 dimensioni


In [ ]:
expandir = np.expand_dims(np.array([1,2,3]),axis=1)
print(expandir)
expandir.ndim

[[1]
 [2]
 [3]]


2

# Cancellare il numero di dimensioni che non vengono utilizzate

In [ ]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(f"i valori del vettore 2 {vector_2} ,il numero de dimensioni del vettore 2 sono: {vector_2.ndim}")


[[[[[[[[[[1 2 3]]]]]]]]]] 10
i valori del vettore 2 [1 2 3] ,il numero de dimensioni del vettore 2 sono: 1


Sumare uno nell'asse X & Y.

In [ ]:
expandirejexy = np.array(["uno",2,"trenta y tres"], ndmin=10)
print(expandirejexy)
expandirejexy.ndim

[[[[[[[[[['uno' '2' 'trenta y tres']]]]]]]]]]


10

In [ ]:
expandirejexy = np.expand_dims(np.array(["uno",2,"trenta y tres"]), axis=0)
print(expandirejexy, expandirejexy.ndim)



[['uno' '2' 'trenta y tres']] 2


In [ ]:
expandirejexy = np.expand_dims(np.array([1,2,4,3]), axis=1)
print(expandirejexy)
print(expandirejexy.ndim)


[[1]
 [2]
 [4]
 [3]]
2


In [ ]:
print(expandirejexy, expandirejexy.ndim)
expandirejexy_2 = np.squeeze(expandirejexy)
print (expandirejexy_2, expandirejexy_2.ndim)

[[1]
 [2]
 [4]
 [3]] 2
[1 2 4 3] 1
