**Guarda Tutte le lezioni di NumPy qui**<br>
➡️➡️ [NumPy Playlist](https://www.youtube.com/watch?v=z0gMBWlScmw&list=PLqzZ6UmyLu115CH8xn6TLxxn8yDn7upOo)<br>
**Se hai qualche domanda o vuoi scrivermi**<br> 🙂
➡️➡️ [Linkedln](https://www.linkedin.com/in/rafaelc1532/)<br>
*Corso di numpy creato da Rafael Carpio*

## Importare librerie

In [ ]:
import numpy as np

### Arange

In [ ]:
list(range(0,10)) #Questo codice non è di numpy, è di python.

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0,20,2) #Questo è un array che va dal 0 al 20 a passi di due

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Zeros

In [ ]:
np.zeros((10,5)) #Permette di definire una struttura previa (array di tipo matrice)
                  #fatto chiaramente con valori di 0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Ones

In [ ]:
np.ones((10,15))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Linspace

In [ ]:
np.linspace(0,10,100) #Con linspace posso specificare, da dove inizio 0, dove finisco 10,
                      #quanti valori voglio generare

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### Eye

In [ ]:
np.eye(4) #Crea una matrice con la diagonale principale composta da uni,
#molto utile in alcuni metodi numerici per la risoluzione di problemi reali, sia lineari che non lineari.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random

In [ ]:
np.random.rand() #Genera un valore casuale tra 0 e 1

0.7247312056316839

In [ ]:
np.random.rand(4) #Array con valori casuali

array([0.23106007, 0.81565235, 0.23571206, 0.79291763])

In [ ]:
np.random.rand(4,4) #Array di due dimensioni con valori casuali

array([[0.57317369, 0.63497674, 0.57233832, 0.81365437],
       [0.11472592, 0.39744642, 0.77631548, 0.1450275 ],
       [0.47698809, 0.30326302, 0.63724452, 0.31140409],
       [0.46257   , 0.15734485, 0.65364284, 0.14718558]])

In [ ]:
np.random.randint(1,15) #Crea un intero casuale tra 1 e 15

12

In [ ]:
np.random.randint(1,100,(10,10)) #Crea una tupla dal 1 al 100 ma di dieci in dieci


array([[51, 93, 13, 49,  5, 46, 39, 68, 89, 16],
       [83, 41, 25, 39, 14, 40, 20, 94, 71, 19],
       [14, 22, 31, 52, 30, 34, 16, 43, 77, 25],
       [27, 53, 28, 25, 22, 71, 12, 80, 15, 18],
       [76, 38, 43, 20, 48, 45, 47, 92,  2, 29],
       [98, 20, 73, 17,  2, 65, 21, 32, 21, 19],
       [ 3, 92, 42, 17, 72, 74, 15, 19, 50, 25],
       [78, 53, 64, 85, 67, 94, 82, 77, 60, 79],
       [15, 29,  6, 60, 39, 68,  5, 70, 35, 86],
       [30, 83, 99, 35, 46, 69, 84, 31, 27, 89]])