### Importar librerías

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,10,(3,2))

### Shape

In [ ]:
arr.shape #shape me dice cuantas filas y cuantas columnas tengo

(3, 2)

In [ ]:
arr

array([[7, 9],
       [4, 8],
       [1, 6]])

### Reshape

In [ ]:
arr.reshape(1,6)

array([[7, 9, 4, 8, 1, 6]])

In [ ]:
arr.reshape(2,3)

array([[7, 9, 4],
       [8, 1, 6]])

In [ ]:
np.reshape(arr,(1,6))

array([[7, 9, 4, 8, 1, 6]])

In [ ]:
arr #Questo è il array originale.

array([[7, 9],
       [4, 8],
       [1, 6]])

In [ ]:
np.reshape(arr,(2,3),'C')

array([[7, 9, 4],
       [8, 1, 6]])

In [ ]:
np.reshape(arr,(2,3),'F')

array([[7, 1, 8],
       [4, 9, 6]])

In [ ]:
np.reshape(arr,(2,3),'A') #Voglio che tu faccia come è ottimizzato
#il salvataggio dei dati nella mia memoria

array([[7, 9, 4],
       [8, 1, 6]])