**Guarda Tutte le lezioni di NumPy qui**<br>
➡️➡️ [NumPy Playlist](https://www.youtube.com/watch?v=z0gMBWlScmw&list=PLqzZ6UmyLu115CH8xn6TLxxn8yDn7upOo)<br>
**Se hai qualche domanda o vuoi scrivermi**<br> 🙂
➡️➡️ [Linkedln](https://www.linkedin.com/in/rafaelc1532/)<br>
*Corso di numpy creato da Rafael Carpio*

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,20,10)
matriz = arr.reshape(2,5)

In [ ]:
arr

array([11,  1,  9,  3,  8,  1, 19, 10, 10, 15])

In [ ]:
matriz

array([[11,  1,  9,  3,  8],
       [ 1, 19, 10, 10, 15]])

# **Funzioni NumPy**

In [ ]:
arr.max()

19

In [ ]:
arr.argmax()

6

In [ ]:
arr.min()

1

In [ ]:
arr.argmin()

1

In [ ]:
matriz.argmax(1)

array([0, 1])

In [ ]:
matriz.argmin(0)

array([1, 0, 0, 0, 0])

**PTP**

In [ ]:
arr.ptp()


18

In [ ]:
matriz.ptp(1)

array([10, 18])

**Sort**

In [ ]:
arr

array([11,  1,  9,  3,  8,  1, 19, 10, 10, 15])

In [ ]:
arr.sort()

In [ ]:
arr

array([ 1,  1,  3,  8,  9, 10, 10, 11, 15, 19])

**Percentile**

In [ ]:
np.percentile(arr,50)

9.5

**Median**

In [ ]:
np.median(arr)

9.5

In [ ]:
np.median(matriz,1)

array([ 3., 11.])

In [ ]:
matriz

array([[ 1,  1,  3,  8,  9],
       [10, 10, 11, 15, 19]])

**Standard Deviation**

In [ ]:
np.std(arr)**2

30.610000000000003

**Var**

In [ ]:
np.var(arr)

30.610000000000003

**Mean**

In [ ]:
np.mean(arr)

8.7

# Concatenate

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [ ]:
np.concatenate((a,b), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
a.ndim

2

In [ ]:
b.ndim

1

**Expand_dims**

In [ ]:
b = np.expand_dims(b,axis=0)

In [ ]:
b.ndim

2

In [ ]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b

array([[5, 6]])

In [ ]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

**Transpuesta**

In [ ]:
b

array([[5, 6]])

In [ ]:
b.T

array([[5],
       [6]])