**Guarda Tutte le lezioni di NumPy qui**<br>
➡️➡️ [NumPy Playlist](https://www.youtube.com/watch?v=z0gMBWlScmw&list=PLqzZ6UmyLu115CH8xn6TLxxn8yDn7upOo)<br>
**Se hai qualche domanda o vuoi scrivermi**<br> 🙂
➡️➡️ [Linkedln](https://www.linkedin.com/in/rafaelc1532/)<br>
*Corso di numpy creato da Rafael Carpio*

*Le Condizioni in Numpy: Un Viaggio Magico 🧙‍♂️ *

In [ ]:
import numpy as np

In [ ]:
arr = np.linspace(1,10,10, dtype='int8')

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
indices_cond = arr > 5

In [ ]:
indices_cond = arr > 5
print(indices_cond)


[False False False False False  True  True  True  True  True]


In [ ]:
print(arr[indices_cond])

[ 6  7  8  9 10]


In [ ]:
print(arr[(arr > 5) & (arr < 9)])

[6 7 8]


In [ ]:
arr[arr > 5] = 99
print(arr)

[ 1  2  3  4  5 99 99 99 99 99]


**🧙‍♀️ Creiamo una matrice 3x3**

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(matrix[1,1])

5


In [ ]:
print(matrix[1, :])

[4 5 6]


In [ ]:
print(matrix[:,0])

[1 4 7]


In [ ]:
print(matrix[matrix > 5])

[6 7 8 9]
