# **Funzione Copy**

**Guarda Tutte le lezioni di NumPy qui**<br>
➡️➡️ [NumPy Playlist](https://www.youtube.com/watch?v=z0gMBWlScmw&list=PLqzZ6UmyLu115CH8xn6TLxxn8yDn7upOo)<br>
**Se hai qualche domanda o vuoi scrivermi**<br> 🙂
➡️➡️ [Linkedln](https://www.linkedin.com/in/rafaelc1532/)<br>
*Corso di numpy creato da Rafael Carpio*


****


#💻 **CODE** 💻

In [ ]:
import numpy as np

In [ ]:
#Creare un array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
pezzo_de_arr = arr[0:6]
pezzo_de_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
pezzo_de_arr[:] = 0
pezzo_de_arr

array([0, 0, 0, 0, 0, 0])

In [ ]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
arr_copiato = arr.copy()


In [ ]:
arr_copiato[:] = 100

In [ ]:
arr_copiato

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
#Array originale
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])